ATIVIDADES_CATALOGO = [
    # SR - Superintendente Regional
    {"nome": "Reunião de Performance Regional", "descricao": "Reunião semanal de análise de performance da regional com todos os gestores.", "periodicidade": "semanal", "perfil": "sr", "obrigatoria": True, "tipo_evidencia": "Ata de reunião ou print do painel", "indicador": "Aderência à rotina gerencial", "ordem": 1},
    {"nome": "Diagnóstico Semanal da Regional", "descricao": "Análise completa dos indicadores comerciais da regional na semana.", "periodicidade": "semanal", "perfil": "sr", "obrigatoria": True, "tipo_evidencia": "Relatório ou dashboard impresso", "indicador": "Funil de vendas regional", "ordem": 2},
    {"nome": "Plano de Ação Semanal Regional", "descricao": "Definição do plano de ação para endereçar gaps identificados na semana.", "periodicidade": "semanal", "perfil": "sr", "obrigatoria": True, "tipo_evidencia": "Documento de plano de ação", "indicador": "Ações implementadas vs planejadas", "ordem": 3},
    {"nome": "Decisões de Canal", "descricao": "Revisão e tomada de decisões sobre canais de venda e parcerias da regional.", "periodicidade": "semanal", "perfil": "sr", "obrigatoria": False, "tipo_evidencia": "Registro de decisões", "indicador": "Decisões de canal executadas", "ordem": 4},
    {"nome": "Top 3 Riscos e Contramedidas", "descricao": "Identificação dos 3 principais riscos da regional e definição de contramedidas.", "periodicidade": "semanal", "perfil": "sr", "obrigatoria": True, "tipo_evidencia": "Documento de riscos atualizado", "indicador": "Riscos mapeados e mitigados", "ordem": 5},
    {"nome": "1:1 com Gerentes de Vendas", "descricao": "Reunião individual com cada Gerente de Vendas para acompanhamento e desenvolvimento.", "periodicidade": "semanal", "perfil": "sr", "obrigatoria": True, "tipo_evidencia": "Registro de 1:1 preenchido", "indicador": "% de 1:1 realizados", "ordem": 6},
    {"nome": "Ciclo Quinzenal de Desenvolvimento", "descricao": "Sessão de desenvolvimento e feedback aprofundado com gestores da regional.", "periodicidade": "quinzenal", "perfil": "sr", "obrigatoria": True, "tipo_evidencia": "PDI ou formulário de feedback", "indicador": "Desenvolvimento de gestores", "ordem": 7},
    {"nome": "Comitê Mensal de Resultado", "descricao": "Comitê mensal com apresentação de resultados, análise e planejamento do próximo período.", "periodicidade": "mensal", "perfil": "sr", "obrigatoria": True, "tipo_evidencia": "Apresentação ou ata do comitê", "indicador": "Meta regional atingida", "ordem": 8},

    # GV - Gerente de Vendas
    {"nome": "Painel do Funil de Vendas", "descricao": "Análise semanal do funil de vendas do time, com acompanhamento de cada etapa.", "periodicidade": "semanal", "perfil": "gv", "obrigatoria": True, "tipo_evidencia": "Print do painel ou planilha de funil", "indicador": "Conversão de funil por etapa", "ordem": 1},
    {"nome": "Plano de Ação do GV", "descricao": "Definição do plano de ação semanal para atingimento de metas e correção de desvios.", "periodicidade": "semanal", "perfil": "gv", "obrigatoria": True, "tipo_evidencia": "Documento de plano de ação assinado", "indicador": "Ações executadas vs planejadas", "ordem": 2},
    {"nome": "Reunião Coletiva com Corretores", "descricao": "Reunião semanal com todo o time de corretores para alinhamento, motivação e treinamento.", "periodicidade": "semanal", "perfil": "gv", "obrigatoria": True, "tipo_evidencia": "Foto ou lista de presença", "indicador": "% de presença dos corretores", "ordem": 3},
    {"nome": "1:1 com Corretores", "descricao": "Reuniões individuais com corretores para acompanhamento de performance e desenvolvimento.", "periodicidade": "semanal", "perfil": "gv", "obrigatoria": True, "tipo_evidencia": "Registro de 1:1 preenchido por corretor", "indicador": "% de 1:1 realizados com time", "ordem": 4},
    {"nome": "Treinamento Semanal do Time", "descricao": "Sessão de treinamento com o time de corretores sobre produtos, técnicas ou processos.", "periodicidade": "semanal", "perfil": "gv", "obrigatoria": True, "tipo_evidencia": "Pauta e lista de presença do treinamento", "indicador": "Horas de treinamento por corretor", "ordem": 5},
    {"nome": "Checagem de Disciplina Operacional", "descricao": "Verificação de presença, agenda preenchida e disciplina da equipe na semana.", "periodicidade": "semanal", "perfil": "gv", "obrigatoria": True, "tipo_evidencia": "Relatório de presença e agenda", "indicador": "% de disciplina operacional", "ordem": 6},
    {"nome": "Controle da Meta Individual", "descricao": "Acompanhamento quinzenal da meta individual de cada corretor e ações de apoio.", "periodicidade": "quinzenal", "perfil": "gv", "obrigatoria": True, "tipo_evidencia": "Planilha de meta individual atualizada", "indicador": "% de atingimento de meta por corretor", "ordem": 7},
    {"nome": "Revisão Mensal de Performance do Time", "descricao": "Análise mensal completa de performance do time com plano de desenvolvimento.", "periodicidade": "mensal", "perfil": "gv", "obrigatoria": True, "tipo_evidencia": "Relatório mensal de performance", "indicador": "Meta do time atingida", "ordem": 8},

    # CD - Coordenador de Empreendimento
    {"nome": "Checklist de Abertura do Stand", "descricao": "Verificação diária/semanal de todos os itens de abertura e funcionamento do stand.", "periodicidade": "semanal", "perfil": "cd", "obrigatoria": True, "tipo_evidencia": "Checklist preenchido e assinado", "indicador": "% de conformidade do stand", "ordem": 1},
    {"nome": "Reunião Rápida do Stand", "descricao": "Reunião de alinhamento semanal com toda a equipe do stand.", "periodicidade": "semanal", "perfil": "cd", "obrigatoria": True, "tipo_evidencia": "Registro de pauta e presença", "indicador": "Aderência às reuniões do stand", "ordem": 2},
    {"nome": "Relatório Geral do Empreendimento", "descricao": "Relatório semanal com dados de visitas, atendimentos, propostas e vendas do empreendimento.", "periodicidade": "semanal", "perfil": "cd", "obrigatoria": True, "tipo_evidencia": "Relatório semanal preenchido", "indicador": "Funil do empreendimento", "ordem": 3},
    {"nome": "Plano Semanal do Empreendimento", "descricao": "Definição das prioridades e ações da semana para o empreendimento.", "periodicidade": "semanal", "perfil": "cd", "obrigatoria": True, "tipo_evidencia": "Documento de plano da semana", "indicador": "Execução do plano semanal", "ordem": 4},
    {"nome": "1-Pager de Concorrência", "descricao": "Análise quinzenal do cenário competitivo do empreendimento com resumo executivo.", "periodicidade": "quinzenal", "perfil": "cd", "obrigatoria": False, "tipo_evidencia": "1-pager de concorrência atualizado", "indicador": "Monitoramento de concorrência", "ordem": 5},
    {"nome": "Relatório Mensal do Empreendimento", "descricao": "Relatório completo mensal com todos os indicadores do empreendimento.", "periodicidade": "mensal", "perfil": "cd", "obrigatoria": True, "tipo_evidencia": "Relatório mensal aprovado", "indicador": "Performance mensal do empreendimento", "ordem": 6},

    # SP - Supervisor de Parcerias
    {"nome": "Relatório do Canal Parcerias", "descricao": "Relatório semanal com resultados do canal de parcerias, visitas e leads gerados.", "periodicidade": "semanal", "perfil": "sp", "obrigatoria": True, "tipo_evidencia": "Relatório do canal preenchido", "indicador": "Leads e vendas por canal de parceria", "ordem": 1},
    {"nome": "Rotina de Visitas a Parceiros", "descricao": "Execução da agenda semanal de visitas a parceiros e imobiliárias parceiras.", "periodicidade": "semanal", "perfil": "sp", "obrigatoria": True, "tipo_evidencia": "Registro de visitas com nome e contato", "indicador": "Nº de visitas realizadas", "ordem": 2},
    {"nome": "Agenda Executada de Parcerias", "descricao": "Registro e validação da agenda executada na semana com parceiros.", "periodicidade": "semanal", "perfil": "sp", "obrigatoria": True, "tipo_evidencia": "Agenda registrada e atualizada", "indicador": "% de agenda executada", "ordem": 3},
    {"nome": "Mapa de Carteira de Parceiros", "descricao": "Atualização quinzenal do mapa de carteira ativa de parceiros e corretores.", "periodicidade": "quinzenal", "perfil": "sp", "obrigatoria": True, "tipo_evidencia": "Mapa de carteira atualizado", "indicador": "Carteira ativa de parceiros", "ordem": 4},
    {"nome": "Plano de Reativação e Expansão", "descricao": "Plano quinzenal para reativação de parceiros inativos e expansão da carteira.", "periodicidade": "quinzenal", "perfil": "sp", "obrigatoria": False, "tipo_evidencia": "Plano de reativação documentado", "indicador": "Parceiros reativados e novos", "ordem": 5},
    {"nome": "Treinamento e Alinhamento com Parceiros", "descricao": "Sessão mensal de treinamento ou alinhamento estratégico com parceiros da carteira.", "periodicidade": "mensal", "perfil": "sp", "obrigatoria": True, "tipo_evidencia": "Lista de presença ou registro do treinamento", "indicador": "Parceiros treinados", "ordem": 6},
]
